services:
  # --- BASE DE DONNÉES ---
  postgres:
    image: postgres:15
    container_name: etl-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etl
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etl-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- STOCKAGE OBJET ---
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - etl-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - etl-network
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 admin password123 &&
      mc mb --ignore-existing local/etl-data &&
      echo '✅ Bucket etl-data créé'
      "

# --- ORCHESTRATEUR ---
  airflow:
    image: apache/airflow:2.8.1
    container_name: airflow
    # On repasse en root (0) pour pouvoir installer Java, puis on repassera en airflow (50000)
    user: "0" 
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@etl-postgres:5432/etl
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "supersecretkey123"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      PYTHONPATH: /opt/airflow
      # Ajout de JAVA_HOME pour que Spark sache où est Java
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    volumes:
      - ../dags:/opt/airflow/dags
      - ../src:/opt/airflow/src
      - ../data:/opt/airflow/data
      - ../logs:/opt/airflow/logs
      - ../docker:/opt/airflow/docker
    networks:
      - etl-network
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "
      apt-get update && apt-get install -y default-jre &&
      su -s /bin/bash airflow -c \"
      pip install --upgrade pip -q &&
      pip install minio python-dotenv requests beautifulsoup4 pandas pyspark psycopg2-binary -q &&
      airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com 2>/dev/null || true &&
      (airflow webserver & airflow scheduler)
      \""

networks:
  etl-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data: